# Generated by Django 4.2.26 on 2025-11-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(default='General', max_length=50)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('read_time', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
